-- YAKIT OTOMASYONU V5 - Supabase SQL Editor'da bir kez çalıştırın.
create extension if not exists pgcrypto;
create table if not exists public.fuel_customer_rules (
 id uuid primary key default gen_random_uuid(), customer text unique not null, provider text not null, city text not null, district text not null, fuel text not null default 'Motorin',
 base_price numeric not null, last_observed_price numeric, threshold numeric not null, factor numeric not null, inclusive boolean not null default true,
 kind text not null, storage_key text, history_key text, active boolean not null default true, last_result text, last_checked_at timestamptz, created_at timestamptz default now(), updated_at timestamptz default now()
);
create table if not exists public.fuel_tariff_state (
 id uuid primary key default gen_random_uuid(), customer text unique not null, kind text not null, payload jsonb not null default '{}'::jsonb, version bigint not null default 1,
 last_base_price numeric,last_fuel_price numeric,last_change_rate numeric,last_applied_rate numeric,created_at timestamptz default now(),updated_at timestamptz default now()
);
create table if not exists public.fuel_price_snapshots (
 id bigint generated by default as identity primary key,customer text not null,provider text,city text,district text,fuel text,base_price numeric,previous_price numeric,current_price numeric,change_rate numeric,rule_passed boolean,checked_at timestamptz default now()
);
create table if not exists public.fuel_automation_runs (
 id bigint generated by default as identity primary key,trigger text,status text,started_at timestamptz,finished_at timestamptz,results jsonb not null default '[]'::jsonb,created_at timestamptz default now()
);
create table if not exists public.fuel_notifications (
 id bigint generated by default as identity primary key,customer text,title text not null,message text not null,type text default 'info',action_path text default '/yakit-hesaplama',read boolean default false,created_at timestamptz default now()
);
create index if not exists idx_fuel_snap_customer_date on public.fuel_price_snapshots(customer,checked_at desc);
create index if not exists idx_fuel_notice_date on public.fuel_notifications(created_at desc);
alter table public.fuel_customer_rules enable row level security;
alter table public.fuel_tariff_state enable row level security;
alter table public.fuel_price_snapshots enable row level security;
alter table public.fuel_automation_runs enable row level security;
alter table public.fuel_notifications enable row level security;
-- Backend SERVICE ROLE kullanır; service_role RLS'yi bypass eder. Anahtar frontend'e KONULMAMALIDIR.
