-- V5.2 - idempotent ve atomik eskalasyon uygulama
create table if not exists public.fuel_escalation_events (
 id bigint generated by default as identity primary key,
 event_key text unique not null,
 customer text not null,
 base_price numeric not null,
 current_price numeric not null,
 change_rate numeric not null,
 applied_rate numeric not null,
 tariff_version bigint,
 created_at timestamptz default now()
);
alter table public.fuel_escalation_events enable row level security;

create or replace function public.apply_fuel_escalation(
 p_event_key text,
 p_customer text,
 p_kind text,
 p_payload jsonb,
 p_base_price numeric,
 p_current_price numeric,
 p_change_rate numeric,
 p_applied_rate numeric,
 p_tariff_version bigint
) returns jsonb
language plpgsql security definer set search_path = public as $$
begin
  if exists(select 1 from fuel_escalation_events where event_key=p_event_key) then
    return jsonb_build_object('applied',false,'duplicate',true);
  end if;

  insert into fuel_escalation_events(event_key,customer,base_price,current_price,change_rate,applied_rate,tariff_version)
  values(p_event_key,p_customer,p_base_price,p_current_price,p_change_rate,p_applied_rate,p_tariff_version);

  insert into fuel_tariff_state(customer,kind,payload,version,last_base_price,last_fuel_price,last_change_rate,last_applied_rate,updated_at)
  values(p_customer,p_kind,p_payload,p_tariff_version,p_base_price,p_current_price,p_change_rate,p_applied_rate,now())
  on conflict(customer) do update set
    kind=excluded.kind,payload=excluded.payload,version=excluded.version,last_base_price=excluded.last_base_price,
    last_fuel_price=excluded.last_fuel_price,last_change_rate=excluded.last_change_rate,last_applied_rate=excluded.last_applied_rate,updated_at=now();

  update fuel_customer_rules set base_price=p_current_price,last_observed_price=p_current_price,last_result='applied',last_checked_at=now(),updated_at=now()
  where customer=p_customer;

  return jsonb_build_object('applied',true,'duplicate',false);
exception when unique_violation then
  return jsonb_build_object('applied',false,'duplicate',true);
end; $$;
