-- FASDAT V6 - Excel tarifeleri + TON/TL geçmişi
-- Mevcut yakit_musterileri.id BIGINT yapısıyla uyumludur.
create table if not exists public.yakit_alis_tarifeleri (
 id bigint generated by default as identity primary key,
 musteri_id bigint not null references public.yakit_musterileri(id) on delete cascade,
 il text not null, ilce text not null, koy_mahalle text,
 hammadde_miktar_ton numeric(14,3), ton_tl numeric(14,4) not null,
 aktif boolean not null default true, created_at timestamptz not null default now(), updated_at timestamptz not null default now()
);
create table if not exists public.yakit_satis_tarifeleri (like public.yakit_alis_tarifeleri including all);
alter table public.yakit_satis_tarifeleri drop constraint if exists yakit_satis_tarifeleri_musteri_id_fkey;
alter table public.yakit_satis_tarifeleri add constraint yakit_satis_tarifeleri_musteri_id_fkey foreign key(musteri_id) references public.yakit_musterileri(id) on delete cascade;
create table if not exists public.yakit_ton_tl_gecmisi (
 id bigint generated by default as identity primary key,
 musteri_id bigint not null references public.yakit_musterileri(id) on delete cascade,
 tarife_tipi text not null check(tarife_tipi in ('alis','satis')), tarife_id bigint,
 il text not null, ilce text not null, koy_mahalle text, hammadde_miktar_ton numeric(14,3),
 eski_ton_tl numeric(14,4) not null, yeni_ton_tl numeric(14,4) not null,
 eski_yakit_fiyati numeric(14,4) not null, yeni_yakit_fiyati numeric(14,4) not null,
 yakit_degisim_orani numeric(14,8) not null, uygulanan_artis_orani numeric(14,8) not null,
 created_at timestamptz not null default now()
);
alter table public.yakit_alis_tarifeleri enable row level security;
alter table public.yakit_satis_tarifeleri enable row level security;
alter table public.yakit_ton_tl_gecmisi enable row level security;
do $$ begin
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='yakit_alis_tarifeleri' and policyname='auth_all') then create policy auth_all on public.yakit_alis_tarifeleri for all to authenticated using(true) with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='yakit_satis_tarifeleri' and policyname='auth_all') then create policy auth_all on public.yakit_satis_tarifeleri for all to authenticated using(true) with check(true); end if;
 if not exists(select 1 from pg_policies where schemaname='public' and tablename='yakit_ton_tl_gecmisi' and policyname='auth_all') then create policy auth_all on public.yakit_ton_tl_gecmisi for all to authenticated using(true) with check(true); end if;
end $$;
grant select,insert,update,delete on public.yakit_alis_tarifeleri,public.yakit_satis_tarifeleri,public.yakit_ton_tl_gecmisi to authenticated;
