-- Yakıt Hesaplama V3: alış/satış ayrı tablolar + müşteri bazlı güncelleme kuralı
create table if not exists public.yakit_alis_fiyatlari (
  id bigint generated by default as identity primary key,
  musteri_id bigint not null references public.yakit_musterileri(id) on delete cascade,
  tarih date not null default current_date,
  fiyat numeric(14,4) not null check (fiyat >= 0),
  aciklama text,
  created_at timestamptz not null default now()
);
create table if not exists public.yakit_satis_fiyatlari (
  id bigint generated by default as identity primary key,
  musteri_id bigint not null references public.yakit_musterileri(id) on delete cascade,
  tarih date not null default current_date,
  fiyat numeric(14,4) not null check (fiyat >= 0),
  aciklama text,
  created_at timestamptz not null default now()
);
create table if not exists public.yakit_hesaplama_kurallari (
  musteri_id bigint primary key references public.yakit_musterileri(id) on delete cascade,
  esik_yuzde numeric(8,4) not null default 7 check (esik_yuzde >= 0),
  bolen numeric(12,4) not null default 1 check (bolen > 0),
  updated_at timestamptz not null default now()
);
create index if not exists yakit_alis_musteri_tarih_idx on public.yakit_alis_fiyatlari(musteri_id,tarih desc,created_at desc);
create index if not exists yakit_satis_musteri_tarih_idx on public.yakit_satis_fiyatlari(musteri_id,tarih desc,created_at desc);

-- V2 verilerini bir defaya mahsus ayırır.
insert into public.yakit_alis_fiyatlari(musteri_id,tarih,fiyat,aciklama,created_at)
select musteri_id,tarih,alis_fiyati,aciklama,created_at from public.yakit_fiyatlari
where alis_fiyati is not null and not exists(select 1 from public.yakit_alis_fiyatlari);
insert into public.yakit_satis_fiyatlari(musteri_id,tarih,fiyat,aciklama,created_at)
select musteri_id,tarih,satis_fiyati,aciklama,created_at from public.yakit_fiyatlari
where satis_fiyati is not null and not exists(select 1 from public.yakit_satis_fiyatlari);
insert into public.yakit_hesaplama_kurallari(musteri_id,esik_yuzde,bolen)
select id,7,1 from public.yakit_musterileri on conflict(musteri_id) do nothing;

alter table public.yakit_alis_fiyatlari enable row level security;
alter table public.yakit_satis_fiyatlari enable row level security;
alter table public.yakit_hesaplama_kurallari enable row level security;

grant select,insert,update on public.yakit_alis_fiyatlari to anon, authenticated;
grant select,insert,update on public.yakit_satis_fiyatlari to anon, authenticated;
grant select,insert,update on public.yakit_hesaplama_kurallari to anon, authenticated;
grant usage,select on all sequences in schema public to anon, authenticated;

create policy "yakit alis read" on public.yakit_alis_fiyatlari for select to anon,authenticated using(true);
create policy "yakit alis insert" on public.yakit_alis_fiyatlari for insert to anon,authenticated with check(true);
create policy "yakit alis update" on public.yakit_alis_fiyatlari for update to anon,authenticated using(true) with check(true);
create policy "yakit satis read" on public.yakit_satis_fiyatlari for select to anon,authenticated using(true);
create policy "yakit satis insert" on public.yakit_satis_fiyatlari for insert to anon,authenticated with check(true);
create policy "yakit satis update" on public.yakit_satis_fiyatlari for update to anon,authenticated using(true) with check(true);
create policy "yakit kural read" on public.yakit_hesaplama_kurallari for select to anon,authenticated using(true);
create policy "yakit kural insert" on public.yakit_hesaplama_kurallari for insert to anon,authenticated with check(true);
create policy "yakit kural update" on public.yakit_hesaplama_kurallari for update to anon,authenticated using(true) with check(true);
