const crypto = require('crypto');
const tls = require('tls');
const fetch = require('node-fetch');
const attempts = new Map();
const challenges = new Map();
const OTP_TTL_MS = 5 * 60 * 1000;
const RESEND_MS = 45 * 1000;
const MAX_ATTEMPTS = 5;
const LOCK_MS = 15 * 60 * 1000;

const b64url = (v) => Buffer.from(v).toString('base64url');
const sha = (v) => crypto.createHash('sha256').update(String(v)).digest('hex');
const maskEmail = (mail='') => { const [a,b] = String(mail).split('@'); if(!b) return 'tanımlı e-posta'; return `${(a||'').slice(0,1)}${'*'.repeat(Math.max(3,(a||'').length-1))}@${b}`; };
function cfg(){return {url:process.env.SUPABASE_URL,key:process.env.SUPABASE_SERVICE_ROLE_KEY,host:process.env.AUTH_SMTP_HOST||process.env.FUEL_SMTP_HOST||process.env.SMTP_HOST||'smtp.office365.com',port:Number(process.env.AUTH_SMTP_PORT||process.env.FUEL_SMTP_PORT||process.env.SMTP_PORT||587),user:process.env.AUTH_SMTP_USER||process.env.FUEL_SMTP_USER||process.env.SMTP_USER||'',pass:process.env.AUTH_SMTP_PASS||process.env.FUEL_SMTP_PASS||process.env.SMTP_PASS||'',from:process.env.AUTH_MAIL_FROM||process.env.FUEL_MAIL_FROM||process.env.SMTP_FROM||'',secret:process.env.AUTH_SESSION_SECRET||process.env.SUPABASE_SERVICE_ROLE_KEY||''};}
async function loginRows(username){const c=cfg(); if(!c.url||!c.key) throw new Error('Supabase sunucu ayarları eksik.'); const q=new URL(`${c.url}/rest/v1/Login`);q.searchParams.set('select','*');q.searchParams.set('kullanici_adi',`eq.${username}`);q.searchParams.set('limit','1');const r=await fetch(q,{headers:{apikey:c.key,Authorization:`Bearer ${c.key}`}});if(!r.ok)throw new Error(`Login tablosu okunamadı (${r.status}).`);return r.json();}
function sendMail(to, code){const c=cfg(); if(!c.user||!c.pass||!c.from) return Promise.reject(new Error('OTP SMTP ayarları eksik.'));return new Promise((resolve,reject)=>{const net=require('net');let socket=net.createConnection(c.port,c.host),buf='';const read=()=>new Promise((res,rej)=>{const on=d=>{buf+=d.toString();if(/\r\n$/.test(buf)){const x=buf;buf='';socket.off('data',on);/^([45])/.test(x)?rej(new Error(x.trim())):res(x)}};socket.on('data',on);socket.once('error',rej)});const write=async x=>{socket.write(x+'\r\n');return read()};(async()=>{try{await read();await write(`EHLO ${c.host}`);await write('STARTTLS');socket=tls.connect({socket,servername:c.host});await new Promise((r,j)=>{socket.once('secureConnect',r);socket.once('error',j)});buf='';await write(`EHLO ${c.host}`);await write('AUTH LOGIN');await write(Buffer.from(c.user).toString('base64'));await write(Buffer.from(c.pass).toString('base64'));await write(`MAIL FROM:<${c.from}>`);await write(`RCPT TO:<${to}>`);await write('DATA');const subject='Odak Lojistik - Güvenlik Doğrulama Kodu';const body=[`From: ${c.from}`,`To: ${to}`,`Subject: =?UTF-8?B?${Buffer.from(subject).toString('base64')}?=`,'MIME-Version: 1.0','Content-Type: text/plain; charset=UTF-8','',`Odak Lojistik Operasyon Sistemi doğrulama kodunuz: ${code}`,'',`Kod 5 dakika geçerlidir. Bu kodu kimseyle paylaşmayın.`,'','.'].join('\r\n');await write(body);await write('QUIT').catch(()=>{});socket.end();resolve()}catch(e){try{socket.destroy()}catch{}reject(e)}})()});}
function signSession(user){const c=cfg();const payload=b64url(JSON.stringify({sub:user.id,name:user.kullanici,role:user.rol,iat:Date.now(),exp:Date.now()+8*60*60*1000}));const sig=crypto.createHmac('sha256',c.secret).update(payload).digest('base64url');return `${payload}.${sig}`;}
function safeUser(u){return {id:u.id,kullanici:u.kullanici,kullanici_adi:u.kullanici_adi,rol:u.rol,allowedScreens:u.allowedScreens,allowedButtons:u.allowedButtons,Reel_kullanici:u.Reel_kullanici,Reel_sifre:u.Reel_sifre};}
function install(app){
 app.get('/api/auth/2fa/health',(req,res)=>res.json({ok:true,service:'email-2fa',smtpConfigured:Boolean(cfg().user&&cfg().pass&&cfg().from),supabaseConfigured:Boolean(cfg().url&&cfg().key)}));
 app.post('/api/auth/2fa/start',async(req,res)=>{try{const username=String(req.body?.username||'').trim(),password=String(req.body?.password||'');if(!username||!password)return res.status(400).json({error:'Kullanıcı adı ve şifre zorunludur.'});const key=username.toLocaleLowerCase('tr-TR');const lock=attempts.get(key);if(lock?.lockedUntil>Date.now())return res.status(429).json({error:'Çok fazla başarısız deneme. 15 dakika sonra tekrar deneyin.'});const rows=await loginRows(username),u=rows?.[0];if(!u||String(u.sifre)!==password){const n=(lock?.count||0)+1;attempts.set(key,{count:n,lockedUntil:n>=MAX_ATTEMPTS?Date.now()+LOCK_MS:0});return res.status(401).json({error:'Kullanıcı adı veya şifre hatalı.'});}if(u.aktif===false)return res.status(403).json({error:'Bu kullanıcı hesabı pasif durumda.'});const email=String(u.email||u.eposta||u.e_posta||(String(u.kullanici_adi).includes('@')?u.kullanici_adi:'')).trim();if(!email.includes('@'))return res.status(409).json({error:'Bu kullanıcı için doğrulama e-posta adresi tanımlı değil. Sistem yöneticinizle iletişime geçin.'});const old=[...challenges.values()].find(x=>x.username===key&&x.expiresAt>Date.now());if(old&&Date.now()-old.sentAt<RESEND_MS)return res.status(429).json({error:'Yeni kod istemeden önce kısa bir süre bekleyin.',retryAfter:Math.ceil((RESEND_MS-(Date.now()-old.sentAt))/1000)});const code=String(crypto.randomInt(100000,1000000)),id=crypto.randomUUID(),salt=crypto.randomBytes(16).toString('hex');challenges.set(id,{username:key,user:u,email,hash:sha(`${salt}:${code}`),salt,expiresAt:Date.now()+OTP_TTL_MS,sentAt:Date.now(),tries:0});await sendMail(email,code);attempts.delete(key);res.json({challengeId:id,maskedEmail:maskEmail(email),expiresIn:300,resendAfter:45});}catch(e){console.error('2FA start:',e);res.status(500).json({error:'Doğrulama kodu gönderilemedi.',detail:process.env.NODE_ENV==='development'?e.message:undefined});}});
 app.post('/api/auth/2fa/verify',(req,res)=>{const id=String(req.body?.challengeId||''),code=String(req.body?.code||'').replace(/\D/g,'');const ch=challenges.get(id);if(!ch)return res.status(400).json({error:'Doğrulama oturumu bulunamadı. Yeniden giriş yapın.'});if(Date.now()>ch.expiresAt){challenges.delete(id);return res.status(410).json({error:'Doğrulama kodunun süresi doldu.'});}ch.tries++;if(ch.tries>MAX_ATTEMPTS){challenges.delete(id);return res.status(429).json({error:'Çok fazla hatalı kod denemesi. Yeniden giriş yapın.'});}const actual=Buffer.from(sha(`${ch.salt}:${code}`),'hex'),expected=Buffer.from(ch.hash,'hex');if(actual.length!==expected.length||!crypto.timingSafeEqual(actual,expected))return res.status(401).json({error:`Doğrulama kodu hatalı. ${MAX_ATTEMPTS-ch.tries} deneme hakkınız kaldı.`});challenges.delete(id);const user=safeUser(ch.user);res.json({ok:true,user,sessionToken:signSession(user),expiresIn:28800});});
}
module.exports={install};
