import React, { useId, useMemo, useState } from "react";
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from "recharts";
import { BarChart3, MapPin, TrendingUp } from "lucide-react";
import { locationKey } from "./useFuelLocationPrices";
const fmt=v=>Number.isFinite(v)?v.toLocaleString("tr-TR",{minimumFractionDigits:2,maximumFractionDigits:2}):"—";
const dateFmt=v=>new Date(Number(v)).toLocaleDateString("tr-TR",{day:"numeric",month:"short"});
function PriceTooltip({active,payload,label}){if(!active||!payload?.length)return null;return <div className="fs-trend-tooltip"><b>{new Date(Number(label)).toLocaleString("tr-TR",{day:"numeric",month:"short",hour:"2-digit",minute:"2-digit"})}</b>{payload.filter(p=>p.value!=null).map(p=><div key={p.dataKey}><i style={{background:p.color}}/><span>{p.name}</span><strong>{fmt(Number(p.value))} ₺</strong></div>)}</div>}
export default function FuelPriceTrend({location,history,shell,po,loading}){
  const [range,setRange]=useState(30),[visible,setVisible]=useState({shell:true,po:true});
  const uid=useId().replace(/[^a-zA-Z0-9_-]/g,"");
  const data=useMemo(()=>{
    const keys={shell:locationKey("shell",location.city,location.district),po:locationKey("petrol-ofisi",location.city,location.district)};
    const since=Date.now()-range*86400000,all=[...history];
    [shell,po].filter(Boolean).forEach(p=>all.push(p));
    const rows=new Map();all.filter(p=>Object.values(keys).includes(p.key)&&Date.parse(p.at)>=since&&Date.parse(p.at)<=Date.now()&&p.price>0).forEach(p=>{const t=Date.parse(p.at),kind=p.key===keys.shell?"shell":"po";rows.set(t,{...rows.get(t),time:t,[kind]:p.price});});
    return [...rows.values()].sort((a,b)=>a.time-b.time);
  },[history,location.city,location.district,range,shell,po]);
  const values=data.flatMap(d=>[visible.shell?d.shell:null,visible.po?d.po:null]).filter(v=>Number.isFinite(v));
  const low=values.length?Math.min(...values):null,high=values.length?Math.max(...values):null;
  const toggle=kind=>setVisible(v=>v[kind]&&!v[kind==="shell"?"po":"shell"]?v:{...v,[kind]:!v[kind]});
  const reduced=typeof window!=="undefined"&&window.matchMedia?.("(prefers-reduced-motion: reduce)").matches;
  return <section className="fs-panel fs-trend fs-trend-v2"><div className="fs-trend-heading"><div><span className="fs-section-kicker">PİYASA GÖRÜNÜMÜ</span><h2><BarChart3 size={20}/> Motorin fiyat trendi</h2><p><MapPin size={12}/>{location.city} / {location.district} <span>· KDV dahil</span></p></div><span className={`fs-chart-live ${loading?"loading":""}`}><i/>{loading?"Güncelleniyor":"Kayıtlı veriler"}</span></div>
    <div className="fs-chart-toolbar"><div className="fs-chart-series">{[["shell","Shell",shell?.price],["po","Petrol Ofisi",po?.price]].map(([key,name,value])=><button key={key} type="button" className={`${key} ${visible[key]?"selected":""}`} aria-pressed={visible[key]} onClick={()=>toggle(key)}><i/><span>{name}<b>{fmt(value)} ₺</b></span></button>)}</div><div className="fs-periods" aria-label="Grafik dönemi">{[7,30,90,365].map(n=><button key={n} type="button" aria-pressed={range===n} className={range===n?"selected":""} onClick={()=>setRange(n)}>{n===365?"1 yıl":`${n}G`}</button>)}</div></div>
    <div className="fs-chart-canvas">{data.length?<ResponsiveContainer width="100%" height="100%" minWidth={0}><AreaChart data={data} margin={{top:18,right:15,left:0,bottom:8}} accessibilityLayer><defs>{["shell","po"].map((key,i)=><linearGradient key={key} id={`${uid}-${key}`} x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor={i?"#f04f68":"#f2b01c"} stopOpacity=".32"/><stop offset="100%" stopColor={i?"#f04f68":"#f2b01c"} stopOpacity=".015"/></linearGradient>)}</defs><CartesianGrid vertical={false} stroke="var(--fs-line)" strokeDasharray="4 5"/><XAxis type="number" dataKey="time" domain={["dataMin","dataMax"]} scale="time" tickFormatter={dateFmt} tick={{fontSize:10,fill:"var(--fs-muted)"}} axisLine={false} tickLine={false} minTickGap={50}/><YAxis domain={[min=>Math.floor((min-.3)*10)/10,max=>Math.ceil((max+.3)*10)/10]} tickFormatter={v=>Number(v).toFixed(1)} width={46} tick={{fontSize:10,fill:"var(--fs-muted)"}} axisLine={false} tickLine={false}/><Tooltip content={<PriceTooltip/>} cursor={{stroke:"#94a8bc",strokeDasharray:"4 4"}}/>{visible.shell&&<Area type="monotone" connectNulls dataKey="shell" name="Shell" stroke="#eeb01b" strokeWidth={3} fill={`url(#${uid}-shell)`} dot={{r:3,strokeWidth:2,fill:"var(--fs-card)"}} activeDot={{r:6,strokeWidth:3,stroke:"var(--fs-card)"}} isAnimationActive={!reduced} animationDuration={650}/>} {visible.po&&<Area type="monotone" connectNulls dataKey="po" name="Petrol Ofisi" stroke="#f04f68" strokeWidth={3} fill={`url(#${uid}-po)`} dot={{r:3,strokeWidth:2,fill:"var(--fs-card)"}} activeDot={{r:6,strokeWidth:3,stroke:"var(--fs-card)"}} isAnimationActive={!reduced} animationDuration={650}/>}</AreaChart></ResponsiveContainer>:<div className="fs-chart-empty"><span className="fs-chart-empty-icon"><TrendingUp size={32}/></span><b>{loading?"Seçili konumun fiyatları alınıyor":"Bu konumda henüz fiyat kaydı yok"}</b><span>Başarılı fiyat kontrolleri grafiğe otomatik eklenir.</span></div>}</div>
    <div className="fs-chart-stats"><div><span>Dönem en düşük</span><b>{fmt(low)} <small>₺/L</small></b></div><div><span>Dönem en yüksek</span><b>{fmt(high)} <small>₺/L</small></b></div><div><span>Fiyat gözlemi</span><b>{values.length}<small> kayıt</small></b></div></div><p className="fs-chart-footnote">Noktalar gerçek fiyat kontrollerini gösterir; aradaki çizgiler görsel bağlantıdır.</p>
  </section>
}
