import React, { useMemo, useState } from "react";
import * as XLSX from "xlsx";
import { AlertTriangle, ArrowLeft, ArrowRight, CheckCircle2, HelpCircle, Plus, Save, Sparkles, Ticket, Upload, X } from "lucide-react";
import "./MusteriKurulumSihirbazi.css";

const CATALOG = [
  ["threshold","Eşik","Yakıt değişimi belirlenen yüzdeye ulaştığında kuralı çalıştırır."],
  ["reflection","Yansıtma oranı","Yakıt değişiminin belirli yüzdesini tarifeye uygular."],
  ["round","Normal yuvarlama","Sonucu seçilen hassasiyete en yakın değere yuvarlar."],
  ["ceil","Yukarı yuvarlama","Sonucu 1 / 5 / 10 / 50 / 100 TL adımına yukarı yuvarlar."],
  ["floor","Aşağı yuvarlama","Sonucu seçilen adıma aşağı yuvarlar."],
  ["fixed","Sabit tutar","Hesaplanan fiyata sabit TL ekler veya çıkarır."],
  ["column","Sütun filtresi","Kuralı yalnızca seçilen tarife/araç sütunlarına uygular."],
  ["region","Bölge filtresi","Kuralı yalnızca belirli bölge/rota kayıtlarına uygular."],
  ["minmax","Alt / üst sınır","Uygulanacak değişime minimum veya maksimum sınır koyar."],
];
const rounders = { round: Math.round, ceil: Math.ceil, floor: Math.floor };
const readUser = () => { try { return JSON.parse(localStorage.getItem("loginUser") || "{}"); } catch { return {}; } };
const money = (v) => Number(v || 0).toLocaleString("tr-TR", { style:"currency", currency:"TRY", maximumFractionDigits:2 });
const pct = (v) => `%${Number(v || 0).toLocaleString("tr-TR", { maximumFractionDigits:2 })}`;
const numeric = (v) => typeof v === "number" ? v : Number(String(v ?? "").replace(/\./g, "").replace(",", ".").replace(/[^0-9.-]/g,""));

function createRuleTicket(customer, text, fileName) {
  const key="odak_system_tickets_v1"; let rows=[]; try { rows=JSON.parse(localStorage.getItem(key)||"[]"); } catch {}
  const user=readUser(); const seq=Number(localStorage.getItem("odak_ticket_sequence")||0)+1; localStorage.setItem("odak_ticket_sequence",String(seq));
  const now=new Date().toISOString(); const ticket={id:`TKT-${Date.now()}`,code:`KRL-${new Date().getFullYear()}-${String(seq).padStart(4,"0")}`,category:"feature",priority:"normal",title:`Yeni kural talebi · ${customer||"Yeni müşteri"}`,description:text,steps:`Müşteri: ${customer||"Belirtilmedi"}\nKaynak Excel: ${fileName||"Belirtilmedi"}`,expected:"Talep edilen kuralın kural kataloğuna eklenmesi ve müşteri kurulumunda kullanılabilmesi.",page:"/finans/musteri-kurulum",attachments:[],status:"open",created_at:now,created_by:user.kullanici||user.ad_soyad||user.kullanici_adi||"Kullanıcı",role:String(user.rol||"kullanici").toLowerCase(),history:[{action:"Kural ticketı oluşturuldu",actor:user.kullanici||user.ad_soyad||"Kullanıcı",at:now}]};
  localStorage.setItem(key,JSON.stringify([ticket,...(Array.isArray(rows)?rows:[])].slice(0,40))); window.dispatchEvent(new Event("odak-tickets-changed")); return ticket.code;
}

export default function MusteriKurulumSihirbazi(){
 const [step,setStep]=useState(0), [file,setFile]=useState(null), [sheets,setSheets]=useState([]), [sheet,setSheet]=useState(""), [rows,setRows]=useState([]), [headers,setHeaders]=useState([]);
 const [customer,setCustomer]=useState(""), [tariffType,setTariffType]=useState("alis_satis"), [fuelSource,setFuelSource]=useState("Petrol Ofisi"), [location,setLocation]=useState("");
 const [mapping,setMapping]=useState({route:"",region:"",loading:"",delivery:"",tir:"",kirkayak:"",open:""});
 const [rules,setRules]=useState([{id:Date.now(),threshold:5,operator:">=",reflection:40,rounding:"ceil",precision:50,column:"all",region:"",fixed:0}]);
 const [ticketText,setTicketText]=useState(""),[ticketCode,setTicketCode]=useState(""),[saved,setSaved]=useState(false),[error,setError]=useState("");
 const analysis=useMemo(()=>{ const empties=rows.reduce((n,r)=>n+headers.filter(h=>r[h]===""||r[h]==null).length,0); const sig=new Set(),dups=[]; rows.forEach((r,i)=>{const k=headers.slice(0,3).map(h=>String(r[h]??"")).join("|"); if(k&&sig.has(k))dups.push(i+2); sig.add(k)}); return {count:rows.length,columns:headers.length,empties,duplicates:dups.length};},[rows,headers]);
 const priceColumns=useMemo(()=>headers.filter(h=>rows.slice(0,20).some(r=>Number.isFinite(numeric(r[h]))&&numeric(r[h])>100)),[headers,rows]);
 const preview=useMemo(()=>rows.slice(0,30).flatMap((r,ri)=>{const rule=rules[0]; return priceColumns.slice(0,3).map(col=>{const old=numeric(r[col]); if(!Number.isFinite(old)||old<=0)return null; const raw=old*(1+(Number(rule.threshold)/100)*(Number(rule.reflection)/100))+Number(rule.fixed||0); const p=Number(rule.precision||1); const fn=rounders[rule.rounding]||Math.round; const next=fn(raw/p)*p; return {row:ri+2,col,old,raw,next};}).filter(Boolean)}),[rows,priceColumns,rules]);
 const readExcel=async(e)=>{const f=e.target.files?.[0]; if(!f)return; setError(""); try{const wb=XLSX.read(await f.arrayBuffer(),{type:"array",cellDates:true}); setFile(f); setSheets(wb.SheetNames); const s=wb.SheetNames[0]; setSheet(s); const data=XLSX.utils.sheet_to_json(wb.Sheets[s],{defval:""}); setRows(data); setHeaders(data.length?Object.keys(data[0]):[]); setMapping(m=>({...m,route:Object.keys(data[0]||{})[0]||""}));}catch(err){setError(`Excel okunamadı: ${err.message}`)}};
 const addRule=()=>setRules(v=>[...v,{id:Date.now(),threshold:5,operator:">=",reflection:40,rounding:"round",precision:10,column:"all",region:"",fixed:0}]);
 const updateRule=(id,k,v)=>setRules(rs=>rs.map(r=>r.id===id?{...r,[k]:v}:r));
 const finish=()=>{if(!customer.trim())return setError("Müşteri adı zorunlu."); const payload={id:`CUS-${Date.now()}`,customer:customer.trim(),tariffType,fuelSource,location,fileName:file?.name,sheet,mapping,rules,headers,createdAt:new Date().toISOString(),createdBy:readUser().kullanici||readUser().ad_soyad||"Kullanıcı",version:1,status:"active"}; const key="odak_dynamic_fuel_customers_v1"; let old=[];try{old=JSON.parse(localStorage.getItem(key)||"[]")}catch{} localStorage.setItem(key,JSON.stringify([payload,...old.filter(x=>x.customer!==payload.customer)])); localStorage.setItem(`odak_tariff_import_${payload.id}`,JSON.stringify(rows.slice(0,3000))); window.dispatchEvent(new Event("odak-dynamic-customers-changed")); setSaved(true);};
 const steps=["Excel Yükle","Veri Eşleştir","Müşteri Bilgileri","Kuralları Oluştur","Test & Önizleme","Aktifleştir"];
 return <div className="mk-page"><div className="mk-hero"><div><span>YENİ MÜŞTERİ KURULUM SİHİRBAZI</span><h1>Excel'den dinamik tarife ve kural oluşturun</h1><p>Tarife dosyasını analiz edin, müşteri kurallarını kod yazmadan tanımlayın, örnek sonuçları test edin ve Yakıt Yönetimi'ne aktarın.</p></div><div className="mk-hero-note"><Sparkles size={20}/><b>Nasıl kullanılır?</b><small>Adımları soldan sağa tamamlayın. Hiçbir tarife son adımdaki onaydan önce aktif edilmez.</small></div></div>
 <div className="mk-steps">{steps.map((s,i)=><button key={s} className={`${i===step?"active":""} ${i<step?"done":""}`} onClick={()=>i<=step&&setStep(i)}><i>{i<step?<CheckCircle2 size={16}/>:i+1}</i><span>{s}</span></button>)}</div>
 {error&&<div className="mk-alert"><AlertTriangle size={17}/>{error}<button onClick={()=>setError("")}><X size={15}/></button></div>}
 <section className="mk-card">
 {step===0&&<><Info title="Excel yükleyin">Sistem ilk satırı başlık olarak okur, sütunları ve veri kalitesini analiz eder. XLSX/XLS desteklenir.</Info><label className="mk-drop"><Upload size={34}/><b>{file?file.name:"Tarife Excel'ini buraya yükleyin"}</b><span>{file?`${analysis.count} satır · ${analysis.columns} sütun algılandı`:"Dosya seçmek için tıklayın"}</span><input type="file" accept=".xlsx,.xls" onChange={readExcel}/></label>{file&&<div className="mk-kpis"><Kpi v={analysis.count} l="Satır"/><Kpi v={analysis.columns} l="Sütun"/><Kpi v={analysis.empties} l="Boş hücre"/><Kpi v={analysis.duplicates} l="Olası mükerrer"/></div>}</>}
 {step===1&&<><Info title="Sütunları eşleştirin">Excel başlıklarını sistem alanlarıyla eşleştirin. Emin olmadığınız alanları boş bırakabilirsiniz.</Info><label className="mk-sheet">Excel sayfası<select value={sheet} onChange={e=>setSheet(e.target.value)}>{sheets.map(x=><option key={x}>{x}</option>)}</select></label><div className="mk-grid">{Object.entries({route:"Rota / Hat",region:"Bölge",loading:"Yükleme",delivery:"Teslim noktası",tir:"TIR fiyatı",kirkayak:"Kırkayak",open:"13.60 Açık Dorse"}).map(([k,l])=><label key={k}>{l}<select value={mapping[k]} onChange={e=>setMapping({...mapping,[k]:e.target.value})}><option value="">Seçilmedi</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label>)}</div><div className="mk-table"><table><thead><tr>{headers.slice(0,7).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{rows.slice(0,5).map((r,i)=><tr key={i}>{headers.slice(0,7).map(h=><td key={h}>{String(r[h]??"")}</td>)}</tr>)}</tbody></table></div></>}
 {step===2&&<><Info title="Müşteriyi tanımlayın">Bu bilgiler Yakıt Yönetimi, onaylar, bildirimler ve işlem geçmişinde müşteriyi tanımlar.</Info><div className="mk-grid"><label>Müşteri adı<input value={customer} onChange={e=>setCustomer(e.target.value)} placeholder="Örn. BİM"/></label><label>Tarife tipi<select value={tariffType} onChange={e=>setTariffType(e.target.value)}><option value="alis_satis">Alış + Satış</option><option value="alis">Alış</option><option value="satis">Satış</option><option value="lowbed">Lowbed</option></select></label><label>Yakıt referansı<select value={fuelSource} onChange={e=>setFuelSource(e.target.value)}><option>Petrol Ofisi</option><option>Shell</option><option>Manuel</option><option>Diğer</option></select></label><label>Referans lokasyonu<input value={location} onChange={e=>setLocation(e.target.value)} placeholder="Örn. İstanbul / Sancaktepe"/></label></div></>}
 {step===3&&<><Info title="Kural motoru">Eşik, yansıtma ve yuvarlamayı müşteri bazında tanımlayın. Birden fazla kural ekleyebilirsiniz.</Info><div className="mk-catalog">{CATALOG.map(([k,t,d])=><div key={k}><b>{t}</b><small>{d}</small></div>)}</div>{rules.map((r,idx)=><div className="mk-rule" key={r.id}><header><b>Kural {idx+1}</b>{rules.length>1&&<button onClick={()=>setRules(rs=>rs.filter(x=>x.id!==r.id))}><X size={15}/></button>}</header><div className="mk-grid rules"><label>Yakıt eşiği (%)<input type="number" value={r.threshold} onChange={e=>updateRule(r.id,"threshold",e.target.value)}/></label><label>Koşul<select value={r.operator} onChange={e=>updateRule(r.id,"operator",e.target.value)}><option value=">=">Geçer veya eşitse</option><option value=">">Geçerse</option></select></label><label>Yansıtma (%)<input type="number" value={r.reflection} onChange={e=>updateRule(r.id,"reflection",e.target.value)}/></label><label>Yuvarlama<select value={r.rounding} onChange={e=>updateRule(r.id,"rounding",e.target.value)}><option value="round">Normal</option><option value="ceil">Yukarı</option><option value="floor">Aşağı</option></select></label><label>Hassasiyet<select value={r.precision} onChange={e=>updateRule(r.id,"precision",Number(e.target.value))}>{[1,5,10,50,100].map(x=><option key={x} value={x}>{x} TL</option>)}</select></label><label>Sabit tutar (TL)<input type="number" value={r.fixed} onChange={e=>updateRule(r.id,"fixed",e.target.value)}/></label><label>Uygulanacak sütun<select value={r.column} onChange={e=>updateRule(r.id,"column",e.target.value)}><option value="all">Tüm fiyat sütunları</option>{headers.map(h=><option key={h}>{h}</option>)}</select></label><label>Bölge/rota filtresi<input value={r.region} onChange={e=>updateRule(r.id,"region",e.target.value)} placeholder="Boş = tümü"/></label></div></div>)}<button className="mk-add" onClick={addRule}><Plus size={16}/> Ek kural oluştur</button><div className="mk-ticket"><div><Ticket size={22}/><span><b>İhtiyacınız olan kural yok mu?</b><small>İstediğiniz özel hesabı anlatın; müşteri ve Excel bilgileriyle Kural Ticketı oluşturalım.</small></span></div><textarea value={ticketText} onChange={e=>setTicketText(e.target.value)} placeholder="Örn. Değişim %8'i geçerse yalnızca İstanbul TIR satırlarında %60 yansıt ve 50 TL yukarı yuvarla..."/><button disabled={ticketText.trim().length<10} onClick={()=>setTicketCode(createRuleTicket(customer,ticketText,file?.name))}><Ticket size={15}/> Kural ticketı oluştur</button>{ticketCode&&<strong>{ticketCode} oluşturuldu ve Ticket Merkezi'ne gönderildi.</strong>}</div></>}
 {step===4&&<><Info title="Test & önizleme">Bu test gerçek tarifeyi değiştirmez. İlk satırlardaki sayısal fiyat alanlarında kuralın sonucunu gösterir.</Info><div className="mk-kpis"><Kpi v={preview.length} l="Test edilen fiyat"/><Kpi v={rules.length} l="Kural"/><Kpi v={priceColumns.length} l="Fiyat sütunu"/><Kpi v={pct(rules[0]?.threshold)} l="Test değişimi"/></div><div className="mk-table"><table><thead><tr><th>Excel satırı</th><th>Sütun</th><th>Eski</th><th>Ham hesap</th><th>Yuvarlanmış</th></tr></thead><tbody>{preview.slice(0,40).map((x,i)=><tr key={i}><td>{x.row}</td><td>{x.col}</td><td>{money(x.old)}</td><td>{money(x.raw)}</td><td><b>{money(x.next)}</b></td></tr>)}</tbody></table></div></>}
 {step===5&&<>{saved?<div className="mk-success"><CheckCircle2 size={42}/><h2>{customer} aktif edildi</h2><p>Müşteri tanımı, Excel eşleştirmesi ve {rules.length} kural dinamik müşteri kataloğuna kaydedildi.</p><div><span>Kural versiyonu <b>v1</b></span><span>Kaynak <b>{fuelSource}</b></span><span>Tarife <b>{tariffType}</b></span></div></div>:<><Info title="Son kontrol">Aktifleştirdiğinizde müşteri ve kurallar tarayıcıdaki dinamik müşteri kataloğuna kaydedilir. Sonradan yeni Excel yükleyerek versiyonlanabilir.</Info><div className="mk-summary"><h2>{customer||"Müşteri adı bekleniyor"}</h2><p>{file?.name||"Excel seçilmedi"}</p><div><span><small>Yakıt kaynağı</small><b>{fuelSource}</b></span><span><small>Lokasyon</small><b>{location||"—"}</b></span><span><small>Kurallar</small><b>{rules.length}</b></span><span><small>Excel satırı</small><b>{rows.length}</b></span></div></div><button className="mk-activate" onClick={finish}><Save size={17}/> Kuralları onayla ve müşteriyi aktifleştir</button></>}</>}
 </section>
 <footer className="mk-nav"><button disabled={step===0} onClick={()=>setStep(s=>Math.max(0,s-1))}><ArrowLeft size={16}/> Geri</button>{step<5&&<button className="primary" disabled={(step===0&&!file)||(step===2&&!customer.trim())} onClick={()=>setStep(s=>Math.min(5,s+1))}>Devam <ArrowRight size={16}/></button>}</footer></div>
}
function Info({title,children}){return <div className="mk-info"><HelpCircle size={18}/><div><b>{title}</b><span>{children}</span></div></div>}
function Kpi({v,l}){return <div className="mk-kpi"><b>{v}</b><span>{l}</span></div>}
