import React, { useEffect, useMemo, useState } from "react";
import { CheckCircle2, ChevronRight, Clock3, Eye, Fuel, Search, XCircle } from "lucide-react";
import { approveEscalation, approveEscalationBatch, getEscalationQueue, postponeEscalation, rejectEscalation } from "./fuelEscalationEngine";
import { createApprovalStatusNotification } from "./fuelNotifications";
import "./YakitOnayMerkezi.css";

const pct = (v) => `%${Math.abs(Number(v || 0)).toLocaleString("tr-TR", { maximumFractionDigits: 2 })}`;
const money = (v) => Number(v || 0).toLocaleString("tr-TR", { style: "currency", currency: "TRY", maximumFractionDigits: 2 });
const statusText = { pending: "Onay bekliyor", processing: "İşleniyor", completed: "Onaylandı", rejected: "Reddedildi", postponed: "Ertelendi", suspicious: "Kontrol gerekli", notified: "Sadece bildirildi" };
const reasons = ["Yakıt fiyatı doğrulanacak", "Müşteriyle görüşülecek", "Sözleşme kontrol edilecek", "Yanlış hesaplama", "Diğer"];

export default function YakitOnayMerkezi() {
  const [, bump] = useState(0); const [tab, setTab] = useState("pending"); const [selected, setSelected] = useState([]); const [active, setActive] = useState(null); const [rejecting, setRejecting] = useState(null); const [reason, setReason] = useState(reasons[0]); const [note, setNote] = useState(""); const [query, setQuery] = useState(""); const [message, setMessage] = useState("");
  const rows = getEscalationQueue();
  useEffect(() => { const f=()=>bump(v=>v+1); window.addEventListener("odak-escalation-changed",f); return()=>window.removeEventListener("odak-escalation-changed",f); },[]);
  const filtered = useMemo(() => rows.filter(r => { const match=!query || `${r.customer} ${r.id}`.toLowerCase().includes(query.toLowerCase()); if(!match)return false; if(tab==="all")return true; if(tab==="pending")return ["pending","postponed","suspicious"].includes(r.status); if(tab==="approved")return ["processing","completed"].includes(r.status); return r.status===tab; }), [rows, tab, query]);
  const pendingCount=rows.filter(r=>["pending","postponed","suspicious"].includes(r.status)).length, approvedCount=rows.filter(r=>["processing","completed"].includes(r.status)).length, rejectedCount=rows.filter(r=>r.status==="rejected").length;
  const refresh=()=>bump(v=>v+1);
  const approve=(row)=>{ const res=approveEscalation(row.id,note); createApprovalStatusNotification({ escalation: row, status: res.ok?"approved":"error", message: res.reason }); setMessage(res.ok?`${row.customer} onaylandı ve tarifeler güncellendi.`:res.reason); setActive(null); setNote(""); refresh(); };
  const reject=()=>{ const row=rejecting; const res=rejectEscalation(row.id,reason,note); if(res.ok) createApprovalStatusNotification({escalation:row,status:"rejected",message:reason}); setMessage(res.ok?`${row.customer} güncellemesi reddedildi.`:res.reason); setRejecting(null); setNote(""); refresh(); };
  const postpone=(row)=>{ const res=postponeEscalation(row.id,24); if(res.ok) createApprovalStatusNotification({escalation:row,status:"postponed",message:"24 saat ertelendi"}); setMessage(res.ok?"Onay 24 saat ertelendi.":res.reason); setActive(null); refresh(); };
  const batch=()=>{ const chosen=rows.filter(r=>selected.includes(r.id)); const results=approveEscalationBatch(selected); const ok=results.filter(r=>r.ok).length; chosen.forEach((r,i)=>createApprovalStatusNotification({escalation:r,status:results[i]?.ok?"approved":"error",message:results[i]?.reason})); setMessage(`${ok}/${selected.length} güncelleme onaylandı.`); setSelected([]); refresh(); };
  return <main className="approval-page">
    <header className="approval-hero"><div><span>YAKIT YÖNETİMİ</span><h1>Onay Merkezi</h1><p>Yakıt değişimlerinden oluşan tarife güncellemelerini inceleyin, onaylayın, reddedin veya erteleyin.</p></div><div className="approval-hero-icon"><CheckCircle2/></div></header>
    {message&&<div className="approval-message">{message}<button onClick={()=>setMessage("")}>×</button></div>}
    <section className="approval-kpis"><article><Clock3/><div><b>{pendingCount}</b><span>Bekleyen onay</span></div></article><article><CheckCircle2/><div><b>{approvedCount}</b><span>Onaylanan</span></div></article><article><XCircle/><div><b>{rejectedCount}</b><span>Reddedilen</span></div></article><article><Fuel/><div><b>{rows.length}</b><span>Toplam kayıt</span></div></article></section>
    <section className="approval-panel"><div className="approval-toolbar"><div className="approval-tabs">{[["pending","Bekleyen"],["approved","Onaylanan"],["rejected","Reddedilen"],["all","Tümü"]].map(([k,l])=><button className={tab===k?"active":""} onClick={()=>setTab(k)} key={k}>{l}</button>)}</div><label className="approval-search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Müşteri veya onay no ara..."/></label></div>
    {selected.length>0&&<div className="approval-batch"><b>{selected.length} kayıt seçildi</b><span>Seçili güncellemeler tek işlemde uygulanacak.</span><button onClick={batch}><CheckCircle2 size={16}/> Toplu Onayla</button></div>}
    <div className="approval-list">{filtered.length?filtered.map(row=><article className="approval-card" key={row.id}><label className="approval-check">{["pending","postponed","suspicious"].includes(row.status)&&<input type="checkbox" checked={selected.includes(row.id)} onChange={e=>setSelected(v=>e.target.checked?[...v,row.id]:v.filter(x=>x!==row.id))}/>}</label><div className="approval-customer"><div className="approval-avatar">{row.customer?.slice(0,2)}</div><div><b>{row.customer}</b><small>{row.rule?.provider} · {row.rule?.location}</small><em>{row.id}</em></div></div><div className="approval-metric"><small>Yakıt değişimi</small><b className={row.fuelChange>=0?"up":"down"}>{row.fuelChange>=0?"+":"-"}{pct(row.fuelChange)}</b><span>{Number(row.oldFuel).toFixed(2)} → {Number(row.newFuel).toFixed(2)} TL</span></div><div className="approval-metric"><small>Tarifeye uygulanacak</small><b>{row.appliedRate>=0?"+":"-"}{pct(row.appliedRate)}</b><span>{row.affectedRoutes || 0} fiyat alanı</span></div><div className="approval-status"><span className={`status ${row.status}`}>{statusText[row.status]||row.status}</span><small>{new Date(row.created_at).toLocaleString("tr-TR")}</small></div><button className="approval-view" onClick={()=>setActive(row)}><Eye size={16}/> İncele <ChevronRight size={15}/></button></article>):<div className="approval-empty"><CheckCircle2/><h3>Bu filtrede kayıt yok</h3><p>Yeni yakıt değişimleri onay gerektiğinde burada görünecek.</p></div>}</div></section>
    {active&&<div className="approval-modal-backdrop" onMouseDown={()=>setActive(null)}><div className="approval-modal" onMouseDown={e=>e.stopPropagation()}><div className="approval-modal-head"><div><span>{active.id}</span><h2>{active.customer} — Tarife Güncelleme Onayı</h2><p>{active.rule?.provider} · {active.rule?.location} · {active.rule?.fuelType||"Motorin"}</p></div><button onClick={()=>setActive(null)}>×</button></div><div className="approval-flow"><div><small>Referans yakıt</small><b>{money(active.oldFuel)}</b></div><i>→</i><div><small>Yeni yakıt</small><b>{money(active.newFuel)}</b></div><i>→</i><div><small>Yakıt değişimi</small><b>{active.fuelChange>=0?"+":"-"}{pct(active.fuelChange)}</b></div><i>→</i><div className="accent"><small>Tarife değişimi</small><b>{active.appliedRate>=0?"+":"-"}{pct(active.appliedRate)}</b></div></div><div className="approval-rule"><b>Hesaplama açıklaması</b><p>Yakıt fiyatı {pct(active.fuelChange)} değişti. {active.customer} sözleşme eşiği %{active.rule?.threshold}, yansıtma oranı %{active.rule?.factor}. Bu nedenle tarifelere {pct(active.appliedRate)} değişim uygulanacak.</p></div><div className="approval-table-wrap"><table><thead><tr><th>Tarife alanı</th><th>Tür</th><th>Eski değer</th><th>Yeni değer</th><th>Fark</th></tr></thead><tbody>{(active.comparison||[]).slice(0,100).map((r,i)=><tr key={i}><td>{r.path}</td><td>{r.side==="buy"?"Alış":"Satış"}</td><td>{money(r.before)}</td><td><b>{money(r.after)}</b></td><td className={r.difference>=0?"up":"down"}>{r.difference>=0?"+":""}{money(r.difference)}</td></tr>)}</tbody></table></div>{["pending","postponed","suspicious"].includes(active.status)&&<><textarea className="approval-note" value={note} onChange={e=>setNote(e.target.value)} placeholder="Onay notu (isteğe bağlı)"/><div className="approval-modal-actions"><button className="reject" onClick={()=>{setRejecting(active);setActive(null)}}><XCircle size={17}/> Reddet</button><button onClick={()=>postpone(active)}><Clock3 size={17}/> 24 Saat Ertele</button><button className="approve" onClick={()=>approve(active)}><CheckCircle2 size={17}/> Onayla ve Tarifeleri Güncelle</button></div></>}</div></div>}
    {rejecting&&<div className="approval-modal-backdrop"><div className="approval-reject"><h2>Güncellemeyi reddet</h2><p><b>{rejecting.customer}</b> için reddetme nedenini seçin. Bu bilgi işlem geçmişinde saklanacak.</p><label>Reddetme nedeni<select value={reason} onChange={e=>setReason(e.target.value)}>{reasons.map(r=><option key={r}>{r}</option>)}</select></label><label>Açıklama<textarea value={note} onChange={e=>setNote(e.target.value)} placeholder="İsteğe bağlı açıklama..."/></label><div><button onClick={()=>setRejecting(null)}>Vazgeç</button><button className="reject" onClick={reject}>Reddet</button></div></div></div>}
  </main>;
}
