import React,{useCallback,useEffect,useMemo,useState} from 'react';
import {AlertTriangle,BellRing,CheckCircle2,Clock3,Fuel,Mail,MapPin,RefreshCw,TrendingDown,TrendingUp} from 'lucide-react';
import './YakitDegisimMerkezi.css';
import {runAutomaticFuelCheck} from './autoFuelService';
const FUEL_API_BASE=(process.env.REACT_APP_FUEL_API_BASE_URL||process.env.REACT_APP_API_BASE_URL||"").replace(/\/+$/,"");
const fuelUrl=(path)=>`${FUEL_API_BASE}${path}`;
const money=v=>Number.isFinite(Number(v))?`${Number(v).toLocaleString('tr-TR',{minimumFractionDigits:2,maximumFractionDigits:2})} ₺`:'—';
const pct=v=>Number.isFinite(Number(v))?`${Number(v)>=0?'+':''}%${(Number(v)*100).toFixed(2)}`:'—';
export default function YakitDegisimMerkezi(){
 const [prices,setPrices]=useState([]),[status,setStatus]=useState(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[msg,setMsg]=useState('');
 const loadStatus=useCallback(async()=>{const r=await fetch(fuelUrl('/api/fuel-automation/status'));const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Otomasyon durumu alınamadı');setStatus(d);return d},[]);
 const loadLive=useCallback(async()=>{const r=await fetch(fuelUrl('/api/fuel-automation/live'));const d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error||'Anlık yakıt fiyatları alınamadı');setPrices(d.prices||[])},[]);
 const refresh=useCallback(async()=>{setBusy(true);setError('');setMsg('');try{await Promise.all([loadLive(),loadStatus()]);setMsg('Referans yakıt fiyatları güncellendi.')}catch(e){setError(e.message)}finally{setBusy(false)}},[loadLive,loadStatus]);
 useEffect(()=>{refresh();const t=setInterval(()=>{loadLive().catch(()=>{});loadStatus().catch(()=>{})},5*60*1000);return()=>clearInterval(t)},[refresh,loadLive,loadStatus]);
 const apply=async()=>{setBusy(true);setError('');setMsg('');try{const x=await runAutomaticFuelCheck();await Promise.all([loadLive(),loadStatus()]);const n=(x.results||[]).filter(r=>r.tariffUpdated).length;setMsg(n?`${n} müşterinin fiyat tarifesi güncellendi. Sistem bildirimi oluşturuldu ve e-posta gönderimi tetiklendi.`:'Kontrol tamamlandı. Eşiği geçen yeni bir müşteri fiyat değişikliği yok.')}catch(e){setError(e.message)}finally{setBusy(false)}};
 const latest=status?.runs?.[0]; const changed=(latest?.results||[]).filter(x=>x.tariffUpdated).length; const alerting=prices.filter(x=>x.passed).length;
 const notices=useMemo(()=>(status?.notifications||[]).filter(n=>n.type==='success'||String(n.title||'').includes('eskalasyon')).slice(0,8),[status]);
 return <div className="fdm-page">
  <div className="fdm-hero"><div><div className="fdm-kicker"><Fuel size={17}/> YAKIT DEĞİŞİM MERKEZİ</div><h1>Müşteri Yakıt Değişimleri</h1><p>Her müşterinin sözleşmedeki referans noktasını, anlık motorin fiyatını ve eskalasyon durumunu tek ekrandan takip edin.</p></div><div className="fdm-actions"><button className="ghost" onClick={refresh} disabled={busy}><RefreshCw size={17} className={busy?'spin':''}/> Fiyatları Yenile</button><button className="primary" onClick={apply} disabled={busy}><CheckCircle2 size={17}/> Kontrol Et ve Uygula</button></div></div>
  {error&&<div className="fdm-banner error"><AlertTriangle size={18}/>{error}</div>}{msg&&<div className="fdm-banner ok"><CheckCircle2 size={18}/>{msg}</div>}
  <div className="fdm-stats"><div><Fuel/><span>Takip edilen müşteri<b>{prices.length}</b></span></div><div><BellRing/><span>Eşiğe ulaşan<b>{alerting}</b></span></div><div><TrendingUp/><span>Son kontrolde güncellenen<b>{changed}</b></span></div><div><Clock3/><span>Otomatik kontrol<b>Her saat başı</b></span></div></div>
  <section className="fdm-card"><div className="fdm-card-head"><div><h2>Anlık Referans Fiyatları</h2><p>Shell ve Petrol Ofisi resmi kaynaklarından müşterinin tanımlı referansına göre okunur.</p></div><span className="live"><i/> CANLI</span></div><div className="fdm-table-wrap"><table><thead><tr><th>MÜŞTERİ</th><th>KAYNAK / REFERANS</th><th>BAZ FİYAT</th><th>ANLIK FİYAT</th><th>DEĞİŞİM</th><th>EŞİK</th><th>TARİFE ETKİSİ</th><th>DURUM</th></tr></thead><tbody>{prices.map(r=>{const applied=Number(r.change_rate||0)*Number(r.factor||0);return <tr key={r.customer} className={r.passed?'warn':''}><td><strong>{r.customer}</strong><small>{r.fuel}</small></td><td><b>{r.provider}</b><small><MapPin size={12}/>{r.city} / {r.district}</small></td><td>{money(r.base_price)}</td><td className="price">{r.error?'—':money(r.current_price)}</td><td>{r.error?<span className="bad">Hata</span>:Number(r.change_rate)>0?<span className="up"><TrendingUp size={14}/>{pct(r.change_rate)}</span>:Number(r.change_rate)<0?<span className="down"><TrendingDown size={14}/>{pct(r.change_rate)}</span>:<span className="same">%0,00</span>}</td><td>%{(Number(r.threshold||0)*100).toFixed(0)}</td><td>{r.error?'—':pct(applied)}</td><td>{r.error?<span className="pill bad" title={r.error}>Fiyat alınamadı</span>:r.passed?<span className="pill action">Eskalasyon eşiğinde</span>:<span className="pill stable">Normal</span>}</td></tr>})}</tbody></table></div></section>
  <div className="fdm-grid"><section className="fdm-card"><div className="fdm-card-head"><div><h2>Son Müşteri Fiyat Değişiklikleri</h2><p>Tarifeye uygulanan son eskalasyon sonuçları.</p></div></div><div className="fdm-list">{!(latest?.results||[]).filter(x=>x.tariffUpdated).length?<div className="empty">Son kontrolde müşteri tarifesi değişmedi.</div>:(latest.results||[]).filter(x=>x.tariffUpdated).map(x=><div className="event" key={x.customer}><span className="event-icon"><CheckCircle2/></span><div><b>{x.customer}</b><p>{money(x.base)} → {money(x.current)} • Yakıt {pct(x.change)} • Tarifeye {pct(x.applied)}</p></div></div>)}</div></section>
  <section className="fdm-card"><div className="fdm-card-head"><div><h2>Bildirim ve E-posta</h2><p>Müşteri fiyatı değiştiğinde sistem bildirimi oluşur; SMTP tanımlıysa e-posta da gönderilir.</p></div><Mail size={22}/></div><div className="fdm-list">{!notices.length?<div className="empty">Henüz eskalasyon bildirimi yok.</div>:notices.map((n,i)=><div className="event" key={n.id||i}><span className="event-icon bell"><BellRing/></span><div><b>{n.title}</b><p>{n.message}</p><small>{n.created_at?new Date(n.created_at).toLocaleString('tr-TR'):''}</small></div></div>)}</div></section></div>
 </div>
}
